CREATE SCHEMA BOOKLIST;

CREATE TABLE BOOKLIST.USER(
    ID BIGINT NOT NULL,
    NOME CHARACTER VARYING (255) NOT NULL,
    LOGIN CHARACTER VARYING (255) NOT NULL,
    SENHA CHARACTER VARYING (255) NOT NULL,
    CREATION_DATE TIMESTAMP NOT NULL DEFAULT NOW(),
    CREATION_USER_ID BIGINT,
    CONSTRAINT USER_PK PRIMARY KEY (ID)
);

CREATE SEQUENCE BOOKLIST.USER_ID_SEQUENCE;

CREATE TABLE BOOKLIST.BOOK (
    ID BIGINT NOT NULL,
    TITLE CHARACTER VARYING (255) NOT NULL,
    AUTHORS CHARACTER VARYING (255) NOT NULL,
    EDITION INTEGER NOT NULL,
    CREATION_DATE TIMESTAMP NOT NULL DEFAULT NOW(),
    CREATION_USER_ID BIGINT NOT NULL
);

CREATE SEQUENCE BOOKLIST.BOOK_ID_SEQUENCE;

ALTER TABLE BOOKLIST.BOOK ADD CONSTRAINT BOOK_USER_CREATION_ID_FK FOREIGN KEY (CREATION_USER_ID) REFERENCES BOOKLIST.USER (ID);